# Generated by Django 6.0 on 2025-12-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('episodes', models.CharField(max_length=10)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('genres', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=10)),
                ('image_url', models.CharField(default='default.jpg', max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
